# Generated by Django 5.1.6 on 2025-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_remove_team_goal_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
