# Generated by Django 5.1.6 on 2025-02-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_managerpost_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpost',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='managerpost',
            name='title',
            field=models.CharField(default="Manager's Comments", max_length=200),
        ),
    ]
