# Generated by Django 5.1.5 on 2025-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CPD Yr Wyddgrug', max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('home_ground', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
