# Generated by Django 5.1.5 on 2025-02-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
    ]
