# Generated by Django 5.1.5 on 2025-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('home_or_away', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=1)),
                ('goals_for', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_against', models.PositiveIntegerField(blank=True, null=True)),
                ('is_played', models.BooleanField(default=False)),
            ],
        ),
    ]
