# Generated by Django 5.1.5 on 2025-02-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_fixture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='is_played',
            new_name='match_completed',
        ),
    ]
