# Generated by Django 5.1.5 on 2025-02-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_managerpost_playeravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeravailability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='playeravailability',
            name='fixture',
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='match_fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.fixture'),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='status',
            field=models.CharField(choices=[('yes', 'Available'), ('no', 'Not Available')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.managerpost'),
        ),
    ]
