# Generated by Django 5.1.5 on 2025-02-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_rename_match_fixture_playeravailability_fixture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeravailability',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.fixture'),
        ),
    ]
