# Generated by Django 5.1.5 on 2025-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_playeravailability_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_ground',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
    ]
