# Generated by Django 5.1.6 on 2025-02-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
    ]
